# Generated by Django 5.2.5 on 2025-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_city_remove_user_province_user_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
