# Generated by Django 5.2.5 on 2025-08-13 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='users.user')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='users.user')),
            ],
            options={
                'unique_together': {('a', 'b')},
            },
        ),
    ]
